name: Deploy Angular SSR to EC2

on:
  push:
    branches:
      - main  # Se ejecutará cuando haya push en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Usa el secret con la clave privada

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-222-135-56.us-east-2.compute.amazonaws.com 'bash ~/deploy_portfolios.sh BM 4003'